# Generated by Django 4.1 on 2022-09-03 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categories',
            old_name='thumnail',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='producttransactions',
            name='transaction_type',
            field=models.IntegerField(choices=[(1, 'BUY'), (2, 'SELL')]),
        ),
    ]
