# Generated by Django 4.1 on 2022-09-03 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoEcommerceApp', '0004_rename_staff_staffuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='uesr_type',
            new_name='user_type',
        ),
    ]
